/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleStorage_sol_SimpleStorage } from './SimpleStorage_sol_SimpleStorage.js';
export * as factories from './factories/index.js';
export { SimpleStorage_sol_SimpleStorage__factory } from './factories/SimpleStorage_sol_SimpleStorage__factory.js';
